name: BNL Nuclear and Particle Physics Software website
description: The website of the Nuclear and Particle Physics Software (NPPS) group in Brookhaven National Laboratory's Physics Department
url: http://bnlnpps.org
excerpt_separator: <!--more-->
timezone: America/New_York
highlighter: rouge
markdown: kramdown
future: true
exclude: [vendor]
plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-redirect-from
collections:
# Start with items in the navigation bar:
  experiments:
    output: true
    permalink: /experiments/:title.html
  techteams:
    output: true
    permalink: /techteams/:title.html
  software:
    output: true
    permalink: /software/:title.html
  events:
    output: true
    permalink: /events/:title.html
  resources:
    output: true
    permalink: /resources/:title.html
  about:
    output: true
    permalink: /about/:title.html
# All other containers:
  people:
    output: true
    permalink: /people/:title.html
  misc:
    output: true
    permalink: /misc/:title.html
